# Generated by Django 5.0.7 on 2024-07-25 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libra', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mybook',
            name='return_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mybook',
            name='borrow_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
